function [spatial_correlation] = Calculate_Source_Spatial_Correlation(eeg_map, microstate_map)

%%%
% [1] M. M. Micah, M. De Lucia, D. Brunet, and C. M. Michel, ‘Principles of Topographic Analyses for Electrical Neuroimaging’, 
% in Brain Signal Analysis: Advances in Neuroelectric and Neuromagnetic Methods, 
% T. C. Handy, Ed. The MIT Press, 2009, p. 0. doi: 10.7551/mitpress/9780262013086.003.0002.

% Function that returns the timeseries from a brainstorm .mat object (source level analysis)
% 
% Gert Vanhollebeke (02/12/2021 - 02/12/2021)
%
% INPUT:
%   path_to_struct: string array containing the full path to the .mat object (generated by "Generate_Paths_All_Together.m")
%
% OUTPUT:
%   timeseries: N x M matrix containing the timeseries of the .mat object (N = #timeserie; M = #timepoints)
%
%%%

%eeg_map = eeg_map - mean(eeg_map, 1);
%microstate_map = microstate_map - mean(microstate_map, 1);

norm_eeg_map = vecnorm(eeg_map, 2, 1);
norm_microstate_map = vecnorm(microstate_map, 2, 1);

spatial_correlation = sum(eeg_map .* microstate_map, 1) ./ (norm_eeg_map .* norm_microstate_map);
end