function [gev_tot, gev_k] = Calculate_Global_Explained_Variance(data, microstates, labels)

%%%
% [1] M. M. Micah, M. De Lucia, D. Brunet, and C. M. Michel, ‘Principles of Topographic Analyses for Electrical Neuroimaging’, 
% in Brain Signal Analysis: Advances in Neuroelectric and Neuromagnetic Methods, 
% T. C. Handy, Ed. The MIT Press, 2009, p. 0. doi: 10.7551/mitpress/9780262013086.003.0002.

% Function that returns the timeseries from a brainstorm .mat object (source level analysis)
% 
% Gert Vanhollebeke (02/12/2021 - 02/12/2021)
%
% INPUT:
%   path_to_struct: string array containing the full path to the .mat object (generated by "Generate_Paths_All_Together.m")
%
% OUTPUT:
%   timeseries: N x M matrix containing the timeseries of the .mat object (N = #timeserie; M = #timepoints)
%
%%%

K = size(microstates,2);
gfp = Calculate_Sensor_Global_Field_Power(data);
segmentation = microstates(:,labels);
gev_k = zeros(1,K);

for k = 1:K
    idx_k = labels==k;
    spatial_correlation_k = Calculate_Spatial_Correlation(data(:,idx_k), segmentation(:,idx_k));
    gev_k(k) = sum((gfp(idx_k) .* spatial_correlation_k).^2) / sum(gfp.^2);

gev_tot = sum(gev_k);

end