function [timeseries] = Extract_Timeseries_From_Structure(path_to_structure)

%%%
% 
% Function that returns the timeseries from a brainstorm .mat object (source level analysis)
% 
% Gert Vanhollebeke (02/12/2021 - 02/12/2021)
%
% INPUT:
%   path_to_struct: string array containing the full path to the .mat object (generated by "Generate_Paths_All_Together.m")
%
% OUTPUT:
%   timeseries: N x M matrix containing the timeseries of the .mat object (N = #timeserie; M = #timepoints)
%
%%%
%Step 0: Tell what is going on.
disp("Obtaining Time Series...");
%Step 1: Load the mat object
participant_structure = load(path_to_structure);
%check the size of the structure, if not (1, 1), keep extracting from the structure until the 2d array is found
while(size(participant_structure,1) == 1 && size(participant_structure,2) == 1)
    structure_fieldnames = fieldnames(participant_structure);
    participant_structure = getfield(participant_structure, structure_fieldnames{1,1});
end
%return the timeseries object
timeseries = participant_structure;
end