function [timeseries] = Extract_Timeseries_From_Sensor_Structure(path_to_structure)

%%%
% 
% Function that returns the timeseries from a .mat object (sensor level analysis)
% 
% Gert Vanhollebeke (28/07/2022 - 28/07/2022)
%
% INPUT:
%   path_to_struct: string array containing the full path to the .mat object (generated by "Generate_Paths_All_Together.m")
%
% OUTPUT:
%   timeseries: N x M matrix containing the timeseries of the .mat object (N = #timeserie; M = #timepoints)
%
%%%
%Step 0: Tell what is going on.
disp("Obtaining Time Series...");
%Step 1: Load the mat object
participant_structure = load(path_to_structure);
%check if the variable is a structure, and not a double
if(isequal(class(participant_structure),'struct'))
    structure_fieldname = fieldnames(participant_structure); %get the field name of the mat object
    timeseries = getfield(participant_structure, structure_fieldname{1,1}); %Get the field with the variable name
    timeseries = timeseries.Value; %Obtain the Value field (always the same for Brainstorm structures
elseif(isequal(class(participant_structure),'double'))
    timeseries = participant_structure; %"structure" is already in the correct form
else
    error('Function: Extract_Timeseries_From_Sensor_Structure.m Reason: data object is neither a structure or double');
end