function [timeseries] = Extract_Timeseries_From_Structure(path_to_structure)

%%%
% 
% Function that returns the timeseries from a .mat object (sensor and source level analysis)
% 
% Gert Vanhollebeke (02/12/2021 - 02/12/2021)
%
% INPUT:
%   path_to_struct: string array containing the full path to the .mat object (generated by "Generate_Paths_All_Together.m")
%
% OUTPUT:
%   timeseries: N x M matrix containing the timeseries of the .mat object (N = #timeserie; M = #timepoints)
%
%%%
%Step 0: Tell what is going on.
disp("Obtaining Time Series...");
%Step 1: Load the mat object
participant_structure = load(path_to_structure);
structure_fieldname = fieldnames(participant_structure); %get the field name of the mat object
timeseries = getfield(participant_structure, structure_fieldname{1,1}); %Get the field with the variable name
end